<?php

namespace App\Http\Helper;

class Country
{
    public static function getAllCountries(): array
    {
        return [
            [
                "ISO-3166alpha2" => "AD",
                "ISO-3166alpha3" => "AND",
                "ISO-3166numeric" => 20,
                "fips" => "AN",
                "Country" => "Andorra",
                "Capital" => "Andorra la Vella",
                "Area in km²" => 468,
                "Population" => 77006,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "AE",
                "ISO-3166alpha3" => "ARE",
                "ISO-3166numeric" => 784,
                "fips" => "AE",
                "Country" => "United Arab Emirates",
                "Capital" => "Abu Dhabi",
                "Area in km²" => 82880,
                "Population" => 9630959,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "AF",
                "ISO-3166alpha3" => "AFG",
                "ISO-3166numeric" => 4,
                "fips" => "AF",
                "Country" => "Afghanistan",
                "Capital" => "Kabul",
                "Area in km²" => 647500,
                "Population" => 37172386,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "AG",
                "ISO-3166alpha3" => "ATG",
                "ISO-3166numeric" => 28,
                "fips" => "AC",
                "Country" => "Antigua and Barbuda",
                "Capital" => "St. John's",
                "Area in km²" => 443,
                "Population" => 96286,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "AI",
                "ISO-3166alpha3" => "AIA",
                "ISO-3166numeric" => 660,
                "fips" => "AV",
                "Country" => "Anguilla",
                "Capital" => "The Valley",
                "Area in km²" => 102,
                "Population" => 13254,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "AL",
                "ISO-3166alpha3" => "ALB",
                "ISO-3166numeric" => 8,
                "fips" => "AL",
                "Country" => "Albania",
                "Capital" => "Tirana",
                "Area in km²" => 28748,
                "Population" => 2866376,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "AM",
                "ISO-3166alpha3" => "ARM",
                "ISO-3166numeric" => 51,
                "fips" => "AM",
                "Country" => "Armenia",
                "Capital" => "Yerevan",
                "Area in km²" => 29800,
                "Population" => 2951776,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "AO",
                "ISO-3166alpha3" => "AGO",
                "ISO-3166numeric" => 24,
                "fips" => "AO",
                "Country" => "Angola",
                "Capital" => "Luanda",
                "Area in km²" => 1246700,
                "Population" => 30809762,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "AQ",
                "ISO-3166alpha3" => "ATA",
                "ISO-3166numeric" => 10,
                "fips" => "AY",
                "Country" => "Antarctica",
                "Capital" => "",
                "Area in km²" => 14000000,
                "Population" => 0,
                "Continent" => "AN"
            ],
            [
                "ISO-3166alpha2" => "AR",
                "ISO-3166alpha3" => "ARG",
                "ISO-3166numeric" => 32,
                "fips" => "AR",
                "Country" => "Argentina",
                "Capital" => "Buenos Aires",
                "Area in km²" => 2766890,
                "Population" => 44494502,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "AS",
                "ISO-3166alpha3" => "ASM",
                "ISO-3166numeric" => 16,
                "fips" => "AQ",
                "Country" => "American Samoa",
                "Capital" => "Pago Pago",
                "Area in km²" => 199,
                "Population" => 55465,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "AT",
                "ISO-3166alpha3" => "AUT",
                "ISO-3166numeric" => 40,
                "fips" => "AU",
                "Country" => "Austria",
                "Capital" => "Vienna",
                "Area in km²" => 83858,
                "Population" => 8847037,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "AU",
                "ISO-3166alpha3" => "AUS",
                "ISO-3166numeric" => 36,
                "fips" => "AS",
                "Country" => "Australia",
                "Capital" => "Canberra",
                "Area in km²" => 7686850,
                "Population" => 24992369,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "AW",
                "ISO-3166alpha3" => "ABW",
                "ISO-3166numeric" => 533,
                "fips" => "AA",
                "Country" => "Aruba",
                "Capital" => "Oranjestad",
                "Area in km²" => 193,
                "Population" => 105845,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "AX",
                "ISO-3166alpha3" => "ALA",
                "ISO-3166numeric" => 248,
                "fips" => "",
                "Country" => "Åland",
                "Capital" => "Mariehamn",
                "Area in km²" => 1580,
                "Population" => 26711,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "AZ",
                "ISO-3166alpha3" => "AZE",
                "ISO-3166numeric" => 31,
                "fips" => "AJ",
                "Country" => "Azerbaijan",
                "Capital" => "Baku",
                "Area in km²" => 86600,
                "Population" => 9942334,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "BA",
                "ISO-3166alpha3" => "BIH",
                "ISO-3166numeric" => 70,
                "fips" => "BK",
                "Country" => "Bosnia and Herzegovina",
                "Capital" => "Sarajevo",
                "Area in km²" => 51129,
                "Population" => 3323929,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "BB",
                "ISO-3166alpha3" => "BRB",
                "ISO-3166numeric" => 52,
                "fips" => "BB",
                "Country" => "Barbados",
                "Capital" => "Bridgetown",
                "Area in km²" => 431,
                "Population" => 286641,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "BD",
                "ISO-3166alpha3" => "BGD",
                "ISO-3166numeric" => 50,
                "fips" => "BG",
                "Country" => "Bangladesh",
                "Capital" => "Dhaka",
                "Area in km²" => 144000,
                "Population" => 161356039,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "BE",
                "ISO-3166alpha3" => "BEL",
                "ISO-3166numeric" => 56,
                "fips" => "BE",
                "Country" => "Belgium",
                "Capital" => "Brussels",
                "Area in km²" => 30510,
                "Population" => 11422068,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "BF",
                "ISO-3166alpha3" => "BFA",
                "ISO-3166numeric" => 854,
                "fips" => "UV",
                "Country" => "Burkina Faso",
                "Capital" => "Ouagadougou",
                "Area in km²" => 274200,
                "Population" => 19751535,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "BG",
                "ISO-3166alpha3" => "BGR",
                "ISO-3166numeric" => 100,
                "fips" => "BU",
                "Country" => "Bulgaria",
                "Capital" => "Sofia",
                "Area in km²" => 110910,
                "Population" => 7000039,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "BH",
                "ISO-3166alpha3" => "BHR",
                "ISO-3166numeric" => 48,
                "fips" => "BA",
                "Country" => "Bahrain",
                "Capital" => "Manama",
                "Area in km²" => 665,
                "Population" => 1569439,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "BI",
                "ISO-3166alpha3" => "BDI",
                "ISO-3166numeric" => 108,
                "fips" => "BY",
                "Country" => "Burundi",
                "Capital" => "Gitega",
                "Area in km²" => 27830,
                "Population" => 11175378,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "BJ",
                "ISO-3166alpha3" => "BEN",
                "ISO-3166numeric" => 204,
                "fips" => "BN",
                "Country" => "Benin",
                "Capital" => "Porto-Novo",
                "Area in km²" => 112620,
                "Population" => 11485048,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "BL",
                "ISO-3166alpha3" => "BLM",
                "ISO-3166numeric" => 652,
                "fips" => "TB",
                "Country" => "Saint Barthélemy",
                "Capital" => "Gustavia",
                "Area in km²" => 21,
                "Population" => 8450,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "BM",
                "ISO-3166alpha3" => "BMU",
                "ISO-3166numeric" => 60,
                "fips" => "BD",
                "Country" => "Bermuda",
                "Capital" => "Hamilton",
                "Area in km²" => 53,
                "Population" => 63968,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "BN",
                "ISO-3166alpha3" => "BRN",
                "ISO-3166numeric" => 96,
                "fips" => "BX",
                "Country" => "Brunei",
                "Capital" => "Bandar Seri Begawan",
                "Area in km²" => 5770,
                "Population" => 428962,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "BO",
                "ISO-3166alpha3" => "BOL",
                "ISO-3166numeric" => 68,
                "fips" => "BL",
                "Country" => "Bolivia",
                "Capital" => "Sucre",
                "Area in km²" => 1098580,
                "Population" => 11353142,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "BQ",
                "ISO-3166alpha3" => "BES",
                "ISO-3166numeric" => 535,
                "fips" => "",
                "Country" => "Bonaire, Sint Eustatius, and Saba",
                "Capital" => "",
                "Area in km²" => 328,
                "Population" => 18012,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "BR",
                "ISO-3166alpha3" => "BRA",
                "ISO-3166numeric" => 76,
                "fips" => "BR",
                "Country" => "Brazil",
                "Capital" => "Brasilia",
                "Area in km²" => 8511965,
                "Population" => 209469333,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "BS",
                "ISO-3166alpha3" => "BHS",
                "ISO-3166numeric" => 44,
                "fips" => "BF",
                "Country" => "Bahamas",
                "Capital" => "Nassau",
                "Area in km²" => 13940,
                "Population" => 385640,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "BT",
                "ISO-3166alpha3" => "BTN",
                "ISO-3166numeric" => 64,
                "fips" => "BT",
                "Country" => "Bhutan",
                "Capital" => "Thimphu",
                "Area in km²" => 47000,
                "Population" => 754394,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "BV",
                "ISO-3166alpha3" => "BVT",
                "ISO-3166numeric" => 74,
                "fips" => "BV",
                "Country" => "Bouvet Island",
                "Capital" => "",
                "Area in km²" => 49,
                "Population" => 0,
                "Continent" => "AN"
            ],
            [
                "ISO-3166alpha2" => "BW",
                "ISO-3166alpha3" => "BWA",
                "ISO-3166numeric" => 72,
                "fips" => "BC",
                "Country" => "Botswana",
                "Capital" => "Gaborone",
                "Area in km²" => 600370,
                "Population" => 2254126,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "BY",
                "ISO-3166alpha3" => "BLR",
                "ISO-3166numeric" => 112,
                "fips" => "BO",
                "Country" => "Belarus",
                "Capital" => "Minsk",
                "Area in km²" => 207600,
                "Population" => 9485386,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "BZ",
                "ISO-3166alpha3" => "BLZ",
                "ISO-3166numeric" => 84,
                "fips" => "BH",
                "Country" => "Belize",
                "Capital" => "Belmopan",
                "Area in km²" => 22966,
                "Population" => 383071,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "CA",
                "ISO-3166alpha3" => "CAN",
                "ISO-3166numeric" => 124,
                "fips" => "CA",
                "Country" => "Canada",
                "Capital" => "Ottawa",
                "Area in km²" => 9984670,
                "Population" => 37058856,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "CC",
                "ISO-3166alpha3" => "CCK",
                "ISO-3166numeric" => 166,
                "fips" => "CK",
                "Country" => "Cocos (Keeling) Islands",
                "Capital" => "West Island",
                "Area in km²" => 14,
                "Population" => 628,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "CD",
                "ISO-3166alpha3" => "COD",
                "ISO-3166numeric" => 180,
                "fips" => "CG",
                "Country" => "DR Congo",
                "Capital" => "Kinshasa",
                "Area in km²" => 2345410,
                "Population" => 84068091,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CF",
                "ISO-3166alpha3" => "CAF",
                "ISO-3166numeric" => 140,
                "fips" => "CT",
                "Country" => "Central African Republic",
                "Capital" => "Bangui",
                "Area in km²" => 622984,
                "Population" => 4666377,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CG",
                "ISO-3166alpha3" => "COG",
                "ISO-3166numeric" => 178,
                "fips" => "CF",
                "Country" => "Congo Republic",
                "Capital" => "Brazzaville",
                "Area in km²" => 342000,
                "Population" => 5244363,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CH",
                "ISO-3166alpha3" => "CHE",
                "ISO-3166numeric" => 756,
                "fips" => "SZ",
                "Country" => "Switzerland",
                "Capital" => "Bern",
                "Area in km²" => 41290,
                "Population" => 8516543,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "CI",
                "ISO-3166alpha3" => "CIV",
                "ISO-3166numeric" => 384,
                "fips" => "IV",
                "Country" => "Ivory Coast",
                "Capital" => "Yamoussoukro",
                "Area in km²" => 322460,
                "Population" => 25069229,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CK",
                "ISO-3166alpha3" => "COK",
                "ISO-3166numeric" => 184,
                "fips" => "CW",
                "Country" => "Cook Islands",
                "Capital" => "Avarua",
                "Area in km²" => 240,
                "Population" => 21388,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "CL",
                "ISO-3166alpha3" => "CHL",
                "ISO-3166numeric" => 152,
                "fips" => "CI",
                "Country" => "Chile",
                "Capital" => "Santiago",
                "Area in km²" => 756950,
                "Population" => 18729160,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "CM",
                "ISO-3166alpha3" => "CMR",
                "ISO-3166numeric" => 120,
                "fips" => "CM",
                "Country" => "Cameroon",
                "Capital" => "Yaounde",
                "Area in km²" => 475440,
                "Population" => 25216237,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CN",
                "ISO-3166alpha3" => "CHN",
                "ISO-3166numeric" => 156,
                "fips" => "CH",
                "Country" => "China",
                "Capital" => "Beijing",
                "Area in km²" => 9596960,
                "Population" => 1411778724,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "CO",
                "ISO-3166alpha3" => "COL",
                "ISO-3166numeric" => 170,
                "fips" => "CO",
                "Country" => "Colombia",
                "Capital" => "Bogota",
                "Area in km²" => 1138910,
                "Population" => 49648685,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "CR",
                "ISO-3166alpha3" => "CRI",
                "ISO-3166numeric" => 188,
                "fips" => "CS",
                "Country" => "Costa Rica",
                "Capital" => "San Jose",
                "Area in km²" => 51100,
                "Population" => 4999441,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "CU",
                "ISO-3166alpha3" => "CUB",
                "ISO-3166numeric" => 192,
                "fips" => "CU",
                "Country" => "Cuba",
                "Capital" => "Havana",
                "Area in km²" => 110860,
                "Population" => 11338138,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "CV",
                "ISO-3166alpha3" => "CPV",
                "ISO-3166numeric" => 132,
                "fips" => "CV",
                "Country" => "Cabo Verde",
                "Capital" => "Praia",
                "Area in km²" => 4033,
                "Population" => 543767,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "CW",
                "ISO-3166alpha3" => "CUW",
                "ISO-3166numeric" => 531,
                "fips" => "UC",
                "Country" => "Curaçao",
                "Capital" => "Willemstad",
                "Area in km²" => 444,
                "Population" => 159849,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "CX",
                "ISO-3166alpha3" => "CXR",
                "ISO-3166numeric" => 162,
                "fips" => "KT",
                "Country" => "Christmas Island",
                "Capital" => "Flying Fish Cove",
                "Area in km²" => 135,
                "Population" => 1500,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "CY",
                "ISO-3166alpha3" => "CYP",
                "ISO-3166numeric" => 196,
                "fips" => "CY",
                "Country" => "Cyprus",
                "Capital" => "Nicosia",
                "Area in km²" => 9250,
                "Population" => 1189265,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "CZ",
                "ISO-3166alpha3" => "CZE",
                "ISO-3166numeric" => 203,
                "fips" => "EZ",
                "Country" => "Czechia",
                "Capital" => "Prague",
                "Area in km²" => 78866,
                "Population" => 10625695,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "DE",
                "ISO-3166alpha3" => "DEU",
                "ISO-3166numeric" => 276,
                "fips" => "GM",
                "Country" => "Germany",
                "Capital" => "Berlin",
                "Area in km²" => 357021,
                "Population" => 82927922,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "DJ",
                "ISO-3166alpha3" => "DJI",
                "ISO-3166numeric" => 262,
                "fips" => "DJ",
                "Country" => "Djibouti",
                "Capital" => "Djibouti",
                "Area in km²" => 23000,
                "Population" => 958920,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "DK",
                "ISO-3166alpha3" => "DNK",
                "ISO-3166numeric" => 208,
                "fips" => "DA",
                "Country" => "Denmark",
                "Capital" => "Copenhagen",
                "Area in km²" => 43094,
                "Population" => 5797446,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "DM",
                "ISO-3166alpha3" => "DMA",
                "ISO-3166numeric" => 212,
                "fips" => "DO",
                "Country" => "Dominica",
                "Capital" => "Roseau",
                "Area in km²" => 754,
                "Population" => 71625,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "DO",
                "ISO-3166alpha3" => "DOM",
                "ISO-3166numeric" => 214,
                "fips" => "DR",
                "Country" => "Dominican Republic",
                "Capital" => "Santo Domingo",
                "Area in km²" => 48730,
                "Population" => 10627165,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "DZ",
                "ISO-3166alpha3" => "DZA",
                "ISO-3166numeric" => 12,
                "fips" => "AG",
                "Country" => "Algeria",
                "Capital" => "Algiers",
                "Area in km²" => 2381740,
                "Population" => 42228429,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "EC",
                "ISO-3166alpha3" => "ECU",
                "ISO-3166numeric" => 218,
                "fips" => "EC",
                "Country" => "Ecuador",
                "Capital" => "Quito",
                "Area in km²" => 283560,
                "Population" => 17084357,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "EE",
                "ISO-3166alpha3" => "EST",
                "ISO-3166numeric" => 233,
                "fips" => "EN",
                "Country" => "Estonia",
                "Capital" => "Tallinn",
                "Area in km²" => 45226,
                "Population" => 1320884,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "EG",
                "ISO-3166alpha3" => "EGY",
                "ISO-3166numeric" => 818,
                "fips" => "EG",
                "Country" => "Egypt",
                "Capital" => "Cairo",
                "Area in km²" => 1001450,
                "Population" => 98423595,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "EH",
                "ISO-3166alpha3" => "ESH",
                "ISO-3166numeric" => 732,
                "fips" => "WI",
                "Country" => "Western Sahara",
                "Capital" => "El-Aaiun",
                "Area in km²" => 266000,
                "Population" => 273008,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ER",
                "ISO-3166alpha3" => "ERI",
                "ISO-3166numeric" => 232,
                "fips" => "ER",
                "Country" => "Eritrea",
                "Capital" => "Asmara",
                "Area in km²" => 121320,
                "Population" => 6209262,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ES",
                "ISO-3166alpha3" => "ESP",
                "ISO-3166numeric" => 724,
                "fips" => "SP",
                "Country" => "Spain",
                "Capital" => "Madrid",
                "Area in km²" => 504782,
                "Population" => 46723749,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "ET",
                "ISO-3166alpha3" => "ETH",
                "ISO-3166numeric" => 231,
                "fips" => "ET",
                "Country" => "Ethiopia",
                "Capital" => "Addis Ababa",
                "Area in km²" => 1127127,
                "Population" => 109224559,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "FI",
                "ISO-3166alpha3" => "FIN",
                "ISO-3166numeric" => 246,
                "fips" => "FI",
                "Country" => "Finland",
                "Capital" => "Helsinki",
                "Area in km²" => 337030,
                "Population" => 5518050,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "FJ",
                "ISO-3166alpha3" => "FJI",
                "ISO-3166numeric" => 242,
                "fips" => "FJ",
                "Country" => "Fiji",
                "Capital" => "Suva",
                "Area in km²" => 18270,
                "Population" => 883483,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "FK",
                "ISO-3166alpha3" => "FLK",
                "ISO-3166numeric" => 238,
                "fips" => "FK",
                "Country" => "Falkland Islands",
                "Capital" => "Stanley",
                "Area in km²" => 12173,
                "Population" => 2638,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "FM",
                "ISO-3166alpha3" => "FSM",
                "ISO-3166numeric" => 583,
                "fips" => "FM",
                "Country" => "Micronesia",
                "Capital" => "Palikir",
                "Area in km²" => 702,
                "Population" => 112640,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "FO",
                "ISO-3166alpha3" => "FRO",
                "ISO-3166numeric" => 234,
                "fips" => "FO",
                "Country" => "Faroe Islands",
                "Capital" => "Torshavn",
                "Area in km²" => 1399,
                "Population" => 48497,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "FR",
                "ISO-3166alpha3" => "FRA",
                "ISO-3166numeric" => 250,
                "fips" => "FR",
                "Country" => "France",
                "Capital" => "Paris",
                "Area in km²" => 547030,
                "Population" => 66987244,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "GA",
                "ISO-3166alpha3" => "GAB",
                "ISO-3166numeric" => 266,
                "fips" => "GB",
                "Country" => "Gabon",
                "Capital" => "Libreville",
                "Area in km²" => 267667,
                "Population" => 2119275,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GB",
                "ISO-3166alpha3" => "GBR",
                "ISO-3166numeric" => 826,
                "fips" => "UK",
                "Country" => "United Kingdom",
                "Capital" => "London",
                "Area in km²" => 244820,
                "Population" => 66488991,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "GD",
                "ISO-3166alpha3" => "GRD",
                "ISO-3166numeric" => 308,
                "fips" => "GJ",
                "Country" => "Grenada",
                "Capital" => "St. George's",
                "Area in km²" => 344,
                "Population" => 111454,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "GE",
                "ISO-3166alpha3" => "GEO",
                "ISO-3166numeric" => 268,
                "fips" => "GG",
                "Country" => "Georgia",
                "Capital" => "Tbilisi",
                "Area in km²" => 69700,
                "Population" => 3731000,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "GF",
                "ISO-3166alpha3" => "GUF",
                "ISO-3166numeric" => 254,
                "fips" => "FG",
                "Country" => "French Guiana",
                "Capital" => "Cayenne",
                "Area in km²" => 91000,
                "Population" => 195506,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "GG",
                "ISO-3166alpha3" => "GGY",
                "ISO-3166numeric" => 831,
                "fips" => "GK",
                "Country" => "Guernsey",
                "Capital" => "St Peter Port",
                "Area in km²" => 78,
                "Population" => 65228,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "GH",
                "ISO-3166alpha3" => "GHA",
                "ISO-3166numeric" => 288,
                "fips" => "GH",
                "Country" => "Ghana",
                "Capital" => "Accra",
                "Area in km²" => 239460,
                "Population" => 29767108,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GI",
                "ISO-3166alpha3" => "GIB",
                "ISO-3166numeric" => 292,
                "fips" => "GI",
                "Country" => "Gibraltar",
                "Capital" => "Gibraltar",
                "Area in km²" => 6.5,
                "Population" => 33718,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "GL",
                "ISO-3166alpha3" => "GRL",
                "ISO-3166numeric" => 304,
                "fips" => "GL",
                "Country" => "Greenland",
                "Capital" => "Nuuk",
                "Area in km²" => 2166086,
                "Population" => 56025,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "GM",
                "ISO-3166alpha3" => "GMB",
                "ISO-3166numeric" => 270,
                "fips" => "GA",
                "Country" => "The Gambia",
                "Capital" => "Banjul",
                "Area in km²" => 11300,
                "Population" => 2280102,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GN",
                "ISO-3166alpha3" => "GIN",
                "ISO-3166numeric" => 324,
                "fips" => "GV",
                "Country" => "Guinea",
                "Capital" => "Conakry",
                "Area in km²" => 245857,
                "Population" => 12414318,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GP",
                "ISO-3166alpha3" => "GLP",
                "ISO-3166numeric" => 312,
                "fips" => "GP",
                "Country" => "Guadeloupe",
                "Capital" => "Basse-Terre",
                "Area in km²" => 1780,
                "Population" => 443000,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "GQ",
                "ISO-3166alpha3" => "GNQ",
                "ISO-3166numeric" => 226,
                "fips" => "EK",
                "Country" => "Equatorial Guinea",
                "Capital" => "Malabo",
                "Area in km²" => 28051,
                "Population" => 1308974,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GR",
                "ISO-3166alpha3" => "GRC",
                "ISO-3166numeric" => 300,
                "fips" => "GR",
                "Country" => "Greece",
                "Capital" => "Athens",
                "Area in km²" => 131940,
                "Population" => 10727668,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "GS",
                "ISO-3166alpha3" => "SGS",
                "ISO-3166numeric" => 239,
                "fips" => "SX",
                "Country" => "South Georgia and South Sandwich Islands",
                "Capital" => "Grytviken",
                "Area in km²" => 3903,
                "Population" => 30,
                "Continent" => "AN"
            ],
            [
                "ISO-3166alpha2" => "GT",
                "ISO-3166alpha3" => "GTM",
                "ISO-3166numeric" => 320,
                "fips" => "GT",
                "Country" => "Guatemala",
                "Capital" => "Guatemala City",
                "Area in km²" => 108890,
                "Population" => 17247807,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "GU",
                "ISO-3166alpha3" => "GUM",
                "ISO-3166numeric" => 316,
                "fips" => "GQ",
                "Country" => "Guam",
                "Capital" => "Hagatna",
                "Area in km²" => 549,
                "Population" => 165768,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "GW",
                "ISO-3166alpha3" => "GNB",
                "ISO-3166numeric" => 624,
                "fips" => "PU",
                "Country" => "Guinea-Bissau",
                "Capital" => "Bissau",
                "Area in km²" => 36120,
                "Population" => 1874309,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "GY",
                "ISO-3166alpha3" => "GUY",
                "ISO-3166numeric" => 328,
                "fips" => "GY",
                "Country" => "Guyana",
                "Capital" => "Georgetown",
                "Area in km²" => 214970,
                "Population" => 779004,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "HK",
                "ISO-3166alpha3" => "HKG",
                "ISO-3166numeric" => 344,
                "fips" => "HK",
                "Country" => "Hong Kong",
                "Capital" => "Hong Kong",
                "Area in km²" => 1092,
                "Population" => 7451000,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "HM",
                "ISO-3166alpha3" => "HMD",
                "ISO-3166numeric" => 334,
                "fips" => "HM",
                "Country" => "Heard and McDonald Islands",
                "Capital" => "",
                "Area in km²" => 412,
                "Population" => 0,
                "Continent" => "AN"
            ],
            [
                "ISO-3166alpha2" => "HN",
                "ISO-3166alpha3" => "HND",
                "ISO-3166numeric" => 340,
                "fips" => "HO",
                "Country" => "Honduras",
                "Capital" => "Tegucigalpa",
                "Area in km²" => 112090,
                "Population" => 9587522,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "HR",
                "ISO-3166alpha3" => "HRV",
                "ISO-3166numeric" => 191,
                "fips" => "HR",
                "Country" => "Croatia",
                "Capital" => "Zagreb",
                "Area in km²" => 56542,
                "Population" => 3871833,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "HT",
                "ISO-3166alpha3" => "HTI",
                "ISO-3166numeric" => 332,
                "fips" => "HA",
                "Country" => "Haiti",
                "Capital" => "Port-au-Prince",
                "Area in km²" => 27750,
                "Population" => 11123176,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "HU",
                "ISO-3166alpha3" => "HUN",
                "ISO-3166numeric" => 348,
                "fips" => "HU",
                "Country" => "Hungary",
                "Capital" => "Budapest",
                "Area in km²" => 93030,
                "Population" => 9768785,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "ID",
                "ISO-3166alpha3" => "IDN",
                "ISO-3166numeric" => 360,
                "fips" => "ID",
                "Country" => "Indonesia",
                "Capital" => "Jakarta",
                "Area in km²" => 1919440,
                "Population" => 267663435,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IE",
                "ISO-3166alpha3" => "IRL",
                "ISO-3166numeric" => 372,
                "fips" => "EI",
                "Country" => "Ireland",
                "Capital" => "Dublin",
                "Area in km²" => 70280,
                "Population" => 4853506,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "IL",
                "ISO-3166alpha3" => "ISR",
                "ISO-3166numeric" => 376,
                "fips" => "IS",
                "Country" => "Israel",
                "Capital" => "Jerusalem",
                "Area in km²" => 20770,
                "Population" => 8883800,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IM",
                "ISO-3166alpha3" => "IMN",
                "ISO-3166numeric" => 833,
                "fips" => "IM",
                "Country" => "Isle of Man",
                "Capital" => "Douglas",
                "Area in km²" => 572,
                "Population" => 84077,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "IN",
                "ISO-3166alpha3" => "IND",
                "ISO-3166numeric" => 356,
                "fips" => "IN",
                "Country" => "India",
                "Capital" => "New Delhi",
                "Area in km²" => 3287590,
                "Population" => 1352617328,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IO",
                "ISO-3166alpha3" => "IOT",
                "ISO-3166numeric" => 86,
                "fips" => "IO",
                "Country" => "British Indian Ocean Territory",
                "Capital" => "Diego Garcia",
                "Area in km²" => 60,
                "Population" => 4000,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IQ",
                "ISO-3166alpha3" => "IRQ",
                "ISO-3166numeric" => 368,
                "fips" => "IZ",
                "Country" => "Iraq",
                "Capital" => "Baghdad",
                "Area in km²" => 437072,
                "Population" => 38433600,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IR",
                "ISO-3166alpha3" => "IRN",
                "ISO-3166numeric" => 364,
                "fips" => "IR",
                "Country" => "Iran",
                "Capital" => "Tehran",
                "Area in km²" => 1648000,
                "Population" => 81800269,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "IS",
                "ISO-3166alpha3" => "ISL",
                "ISO-3166numeric" => 352,
                "fips" => "IC",
                "Country" => "Iceland",
                "Capital" => "Reykjavik",
                "Area in km²" => 103000,
                "Population" => 353574,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "IT",
                "ISO-3166alpha3" => "ITA",
                "ISO-3166numeric" => 380,
                "fips" => "IT",
                "Country" => "Italy",
                "Capital" => "Rome",
                "Area in km²" => 301230,
                "Population" => 60431283,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "JE",
                "ISO-3166alpha3" => "JEY",
                "ISO-3166numeric" => 832,
                "fips" => "JE",
                "Country" => "Jersey",
                "Capital" => "Saint Helier",
                "Area in km²" => 116,
                "Population" => 90812,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "JM",
                "ISO-3166alpha3" => "JAM",
                "ISO-3166numeric" => 388,
                "fips" => "JM",
                "Country" => "Jamaica",
                "Capital" => "Kingston",
                "Area in km²" => 10991,
                "Population" => 2934855,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "JO",
                "ISO-3166alpha3" => "JOR",
                "ISO-3166numeric" => 400,
                "fips" => "JO",
                "Country" => "Jordan",
                "Capital" => "Amman",
                "Area in km²" => 92300,
                "Population" => 9956011,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "JP",
                "ISO-3166alpha3" => "JPN",
                "ISO-3166numeric" => 392,
                "fips" => "JA",
                "Country" => "Japan",
                "Capital" => "Tokyo",
                "Area in km²" => 377835,
                "Population" => 126529100,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KE",
                "ISO-3166alpha3" => "KEN",
                "ISO-3166numeric" => 404,
                "fips" => "KE",
                "Country" => "Kenya",
                "Capital" => "Nairobi",
                "Area in km²" => 582650,
                "Population" => 51393010,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "KG",
                "ISO-3166alpha3" => "KGZ",
                "ISO-3166numeric" => 417,
                "fips" => "KG",
                "Country" => "Kyrgyzstan",
                "Capital" => "Bishkek",
                "Area in km²" => 198500,
                "Population" => 6315800,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KH",
                "ISO-3166alpha3" => "KHM",
                "ISO-3166numeric" => 116,
                "fips" => "CB",
                "Country" => "Cambodia",
                "Capital" => "Phnom Penh",
                "Area in km²" => 181040,
                "Population" => 16249798,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KI",
                "ISO-3166alpha3" => "KIR",
                "ISO-3166numeric" => 296,
                "fips" => "KR",
                "Country" => "Kiribati",
                "Capital" => "Tarawa",
                "Area in km²" => 811,
                "Population" => 115847,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "KM",
                "ISO-3166alpha3" => "COM",
                "ISO-3166numeric" => 174,
                "fips" => "CN",
                "Country" => "Comoros",
                "Capital" => "Moroni",
                "Area in km²" => 2170,
                "Population" => 832322,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "KN",
                "ISO-3166alpha3" => "KNA",
                "ISO-3166numeric" => 659,
                "fips" => "SC",
                "Country" => "St Kitts and Nevis",
                "Capital" => "Basseterre",
                "Area in km²" => 261,
                "Population" => 52441,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "KP",
                "ISO-3166alpha3" => "PRK",
                "ISO-3166numeric" => 408,
                "fips" => "KN",
                "Country" => "North Korea",
                "Capital" => "Pyongyang",
                "Area in km²" => 120540,
                "Population" => 25549819,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KR",
                "ISO-3166alpha3" => "KOR",
                "ISO-3166numeric" => 410,
                "fips" => "KS",
                "Country" => "South Korea",
                "Capital" => "Seoul",
                "Area in km²" => 98480,
                "Population" => 51635256,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KW",
                "ISO-3166alpha3" => "KWT",
                "ISO-3166numeric" => 414,
                "fips" => "KU",
                "Country" => "Kuwait",
                "Capital" => "Kuwait City",
                "Area in km²" => 17820,
                "Population" => 4137309,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "KY",
                "ISO-3166alpha3" => "CYM",
                "ISO-3166numeric" => 136,
                "fips" => "CJ",
                "Country" => "Cayman Islands",
                "Capital" => "George Town",
                "Area in km²" => 262,
                "Population" => 64174,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "KZ",
                "ISO-3166alpha3" => "KAZ",
                "ISO-3166numeric" => 398,
                "fips" => "KZ",
                "Country" => "Kazakhstan",
                "Capital" => "Nur-Sultan",
                "Area in km²" => 2717300,
                "Population" => 18276499,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "LA",
                "ISO-3166alpha3" => "LAO",
                "ISO-3166numeric" => 418,
                "fips" => "LA",
                "Country" => "Laos",
                "Capital" => "Vientiane",
                "Area in km²" => 236800,
                "Population" => 7061507,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "LB",
                "ISO-3166alpha3" => "LBN",
                "ISO-3166numeric" => 422,
                "fips" => "LE",
                "Country" => "Lebanon",
                "Capital" => "Beirut",
                "Area in km²" => 10400,
                "Population" => 6848925,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "LC",
                "ISO-3166alpha3" => "LCA",
                "ISO-3166numeric" => 662,
                "fips" => "ST",
                "Country" => "Saint Lucia",
                "Capital" => "Castries",
                "Area in km²" => 616,
                "Population" => 181889,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "LI",
                "ISO-3166alpha3" => "LIE",
                "ISO-3166numeric" => 438,
                "fips" => "LS",
                "Country" => "Liechtenstein",
                "Capital" => "Vaduz",
                "Area in km²" => 160,
                "Population" => 37910,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "LK",
                "ISO-3166alpha3" => "LKA",
                "ISO-3166numeric" => 144,
                "fips" => "CE",
                "Country" => "Sri Lanka",
                "Capital" => "Colombo",
                "Area in km²" => 65610,
                "Population" => 21670000,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "LR",
                "ISO-3166alpha3" => "LBR",
                "ISO-3166numeric" => 430,
                "fips" => "LI",
                "Country" => "Liberia",
                "Capital" => "Monrovia",
                "Area in km²" => 111370,
                "Population" => 4818977,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "LS",
                "ISO-3166alpha3" => "LSO",
                "ISO-3166numeric" => 426,
                "fips" => "LT",
                "Country" => "Lesotho",
                "Capital" => "Maseru",
                "Area in km²" => 30355,
                "Population" => 2108132,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "LT",
                "ISO-3166alpha3" => "LTU",
                "ISO-3166numeric" => 440,
                "fips" => "LH",
                "Country" => "Lithuania",
                "Capital" => "Vilnius",
                "Area in km²" => 65200,
                "Population" => 2789533,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "LU",
                "ISO-3166alpha3" => "LUX",
                "ISO-3166numeric" => 442,
                "fips" => "LU",
                "Country" => "Luxembourg",
                "Capital" => "Luxembourg",
                "Area in km²" => 2586,
                "Population" => 607728,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "LV",
                "ISO-3166alpha3" => "LVA",
                "ISO-3166numeric" => 428,
                "fips" => "LG",
                "Country" => "Latvia",
                "Capital" => "Riga",
                "Area in km²" => 64589,
                "Population" => 1926542,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "LY",
                "ISO-3166alpha3" => "LBY",
                "ISO-3166numeric" => 434,
                "fips" => "LY",
                "Country" => "Libya",
                "Capital" => "Tripoli",
                "Area in km²" => 1759540,
                "Population" => 6678567,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MA",
                "ISO-3166alpha3" => "MAR",
                "ISO-3166numeric" => 504,
                "fips" => "MO",
                "Country" => "Morocco",
                "Capital" => "Rabat",
                "Area in km²" => 446550,
                "Population" => 36029138,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MC",
                "ISO-3166alpha3" => "MCO",
                "ISO-3166numeric" => 492,
                "fips" => "MN",
                "Country" => "Monaco",
                "Capital" => "Monaco",
                "Area in km²" => 1.9,
                "Population" => 38682,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "MD",
                "ISO-3166alpha3" => "MDA",
                "ISO-3166numeric" => 498,
                "fips" => "MD",
                "Country" => "Moldova",
                "Capital" => "Chisinau",
                "Area in km²" => 33843,
                "Population" => 3545883,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "ME",
                "ISO-3166alpha3" => "MNE",
                "ISO-3166numeric" => 499,
                "fips" => "MJ",
                "Country" => "Montenegro",
                "Capital" => "Podgorica",
                "Area in km²" => 14026,
                "Population" => 622345,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "MF",
                "ISO-3166alpha3" => "MAF",
                "ISO-3166numeric" => 663,
                "fips" => "RN",
                "Country" => "Saint Martin",
                "Capital" => "Marigot",
                "Area in km²" => 53,
                "Population" => 37264,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "MG",
                "ISO-3166alpha3" => "MDG",
                "ISO-3166numeric" => 450,
                "fips" => "MA",
                "Country" => "Madagascar",
                "Capital" => "Antananarivo",
                "Area in km²" => 587040,
                "Population" => 26262368,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MH",
                "ISO-3166alpha3" => "MHL",
                "ISO-3166numeric" => 584,
                "fips" => "RM",
                "Country" => "Marshall Islands",
                "Capital" => "Majuro",
                "Area in km²" => 181.3,
                "Population" => 58413,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "MK",
                "ISO-3166alpha3" => "MKD",
                "ISO-3166numeric" => 807,
                "fips" => "MK",
                "Country" => "North Macedonia",
                "Capital" => "Skopje",
                "Area in km²" => 25333,
                "Population" => 2082958,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "ML",
                "ISO-3166alpha3" => "MLI",
                "ISO-3166numeric" => 466,
                "fips" => "ML",
                "Country" => "Mali",
                "Capital" => "Bamako",
                "Area in km²" => 1240000,
                "Population" => 19077690,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MM",
                "ISO-3166alpha3" => "MMR",
                "ISO-3166numeric" => 104,
                "fips" => "BM",
                "Country" => "Myanmar",
                "Capital" => "Nay Pyi Taw",
                "Area in km²" => 678500,
                "Population" => 53708395,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "MN",
                "ISO-3166alpha3" => "MNG",
                "ISO-3166numeric" => 496,
                "fips" => "MG",
                "Country" => "Mongolia",
                "Capital" => "Ulaanbaatar",
                "Area in km²" => 1565000,
                "Population" => 3170208,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "MO",
                "ISO-3166alpha3" => "MAC",
                "ISO-3166numeric" => 446,
                "fips" => "MC",
                "Country" => "Macao",
                "Capital" => "Macao",
                "Area in km²" => 254,
                "Population" => 631636,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "MP",
                "ISO-3166alpha3" => "MNP",
                "ISO-3166numeric" => 580,
                "fips" => "CQ",
                "Country" => "Northern Mariana Islands",
                "Capital" => "Saipan",
                "Area in km²" => 477,
                "Population" => 56882,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "MQ",
                "ISO-3166alpha3" => "MTQ",
                "ISO-3166numeric" => 474,
                "fips" => "MB",
                "Country" => "Martinique",
                "Capital" => "Fort-de-France",
                "Area in km²" => 1100,
                "Population" => 432900,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "MR",
                "ISO-3166alpha3" => "MRT",
                "ISO-3166numeric" => 478,
                "fips" => "MR",
                "Country" => "Mauritania",
                "Capital" => "Nouakchott",
                "Area in km²" => 1030700,
                "Population" => 4403319,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MS",
                "ISO-3166alpha3" => "MSR",
                "ISO-3166numeric" => 500,
                "fips" => "MH",
                "Country" => "Montserrat",
                "Capital" => "Plymouth",
                "Area in km²" => 102,
                "Population" => 9341,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "MT",
                "ISO-3166alpha3" => "MLT",
                "ISO-3166numeric" => 470,
                "fips" => "MT",
                "Country" => "Malta",
                "Capital" => "Valletta",
                "Area in km²" => 316,
                "Population" => 483530,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "MU",
                "ISO-3166alpha3" => "MUS",
                "ISO-3166numeric" => 480,
                "fips" => "MP",
                "Country" => "Mauritius",
                "Capital" => "Port Louis",
                "Area in km²" => 2040,
                "Population" => 1265303,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MV",
                "ISO-3166alpha3" => "MDV",
                "ISO-3166numeric" => 462,
                "fips" => "MV",
                "Country" => "Maldives",
                "Capital" => "Male",
                "Area in km²" => 300,
                "Population" => 515696,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "MW",
                "ISO-3166alpha3" => "MWI",
                "ISO-3166numeric" => 454,
                "fips" => "MI",
                "Country" => "Malawi",
                "Capital" => "Lilongwe",
                "Area in km²" => 118480,
                "Population" => 17563749,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "MX",
                "ISO-3166alpha3" => "MEX",
                "ISO-3166numeric" => 484,
                "fips" => "MX",
                "Country" => "Mexico",
                "Capital" => "Mexico City",
                "Area in km²" => 1972550,
                "Population" => 126190788,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "MY",
                "ISO-3166alpha3" => "MYS",
                "ISO-3166numeric" => 458,
                "fips" => "MY",
                "Country" => "Malaysia",
                "Capital" => "Kuala Lumpur",
                "Area in km²" => 329750,
                "Population" => 31528585,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "MZ",
                "ISO-3166alpha3" => "MOZ",
                "ISO-3166numeric" => 508,
                "fips" => "MZ",
                "Country" => "Mozambique",
                "Capital" => "Maputo",
                "Area in km²" => 801590,
                "Population" => 29495962,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "NA",
                "ISO-3166alpha3" => "NAM",
                "ISO-3166numeric" => 516,
                "fips" => "WA",
                "Country" => "Namibia",
                "Capital" => "Windhoek",
                "Area in km²" => 825418,
                "Population" => 2448255,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "NC",
                "ISO-3166alpha3" => "NCL",
                "ISO-3166numeric" => 540,
                "fips" => "NC",
                "Country" => "New Caledonia",
                "Capital" => "Noumea",
                "Area in km²" => 19060,
                "Population" => 284060,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "NE",
                "ISO-3166alpha3" => "NER",
                "ISO-3166numeric" => 562,
                "fips" => "NG",
                "Country" => "Niger",
                "Capital" => "Niamey",
                "Area in km²" => 1267000,
                "Population" => 22442948,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "NF",
                "ISO-3166alpha3" => "NFK",
                "ISO-3166numeric" => 574,
                "fips" => "NF",
                "Country" => "Norfolk Island",
                "Capital" => "Kingston",
                "Area in km²" => 34.6,
                "Population" => 1828,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "NG",
                "ISO-3166alpha3" => "NGA",
                "ISO-3166numeric" => 566,
                "fips" => "NI",
                "Country" => "Nigeria",
                "Capital" => "Abuja",
                "Area in km²" => 923768,
                "Population" => 195874740,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "NI",
                "ISO-3166alpha3" => "NIC",
                "ISO-3166numeric" => 558,
                "fips" => "NU",
                "Country" => "Nicaragua",
                "Capital" => "Managua",
                "Area in km²" => 129494,
                "Population" => 6465513,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "NL",
                "ISO-3166alpha3" => "NLD",
                "ISO-3166numeric" => 528,
                "fips" => "NL",
                "Country" => "Netherlands",
                "Capital" => "Amsterdam",
                "Area in km²" => 41526,
                "Population" => 17231017,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "NO",
                "ISO-3166alpha3" => "NOR",
                "ISO-3166numeric" => 578,
                "fips" => "NO",
                "Country" => "Norway",
                "Capital" => "Oslo",
                "Area in km²" => 324220,
                "Population" => 5314336,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "NP",
                "ISO-3166alpha3" => "NPL",
                "ISO-3166numeric" => 524,
                "fips" => "NP",
                "Country" => "Nepal",
                "Capital" => "Kathmandu",
                "Area in km²" => 140800,
                "Population" => 28087871,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "NR",
                "ISO-3166alpha3" => "NRU",
                "ISO-3166numeric" => 520,
                "fips" => "NR",
                "Country" => "Nauru",
                "Capital" => "Yaren",
                "Area in km²" => 21,
                "Population" => 12704,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "NU",
                "ISO-3166alpha3" => "NIU",
                "ISO-3166numeric" => 570,
                "fips" => "NE",
                "Country" => "Niue",
                "Capital" => "Alofi",
                "Area in km²" => 260,
                "Population" => 2166,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "NZ",
                "ISO-3166alpha3" => "NZL",
                "ISO-3166numeric" => 554,
                "fips" => "NZ",
                "Country" => "New Zealand",
                "Capital" => "Wellington",
                "Area in km²" => 268680,
                "Population" => 4885500,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "OM",
                "ISO-3166alpha3" => "OMN",
                "ISO-3166numeric" => 512,
                "fips" => "MU",
                "Country" => "Oman",
                "Capital" => "Muscat",
                "Area in km²" => 212460,
                "Population" => 4829483,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "PA",
                "ISO-3166alpha3" => "PAN",
                "ISO-3166numeric" => 591,
                "fips" => "PM",
                "Country" => "Panama",
                "Capital" => "Panama City",
                "Area in km²" => 78200,
                "Population" => 4176873,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "PE",
                "ISO-3166alpha3" => "PER",
                "ISO-3166numeric" => 604,
                "fips" => "PE",
                "Country" => "Peru",
                "Capital" => "Lima",
                "Area in km²" => 1285220,
                "Population" => 31989256,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "PF",
                "ISO-3166alpha3" => "PYF",
                "ISO-3166numeric" => 258,
                "fips" => "FP",
                "Country" => "French Polynesia",
                "Capital" => "Papeete",
                "Area in km²" => 4167,
                "Population" => 277679,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "PG",
                "ISO-3166alpha3" => "PNG",
                "ISO-3166numeric" => 598,
                "fips" => "PP",
                "Country" => "Papua New Guinea",
                "Capital" => "Port Moresby",
                "Area in km²" => 462840,
                "Population" => 8606316,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "PH",
                "ISO-3166alpha3" => "PHL",
                "ISO-3166numeric" => 608,
                "fips" => "RP",
                "Country" => "Philippines",
                "Capital" => "Manila",
                "Area in km²" => 300000,
                "Population" => 106651922,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "PK",
                "ISO-3166alpha3" => "PAK",
                "ISO-3166numeric" => 586,
                "fips" => "PK",
                "Country" => "Pakistan",
                "Capital" => "Islamabad",
                "Area in km²" => 803940,
                "Population" => 212215030,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "PL",
                "ISO-3166alpha3" => "POL",
                "ISO-3166numeric" => 616,
                "fips" => "PL",
                "Country" => "Poland",
                "Capital" => "Warsaw",
                "Area in km²" => 312685,
                "Population" => 37978548,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "PM",
                "ISO-3166alpha3" => "SPM",
                "ISO-3166numeric" => 666,
                "fips" => "SB",
                "Country" => "Saint Pierre and Miquelon",
                "Capital" => "Saint-Pierre",
                "Area in km²" => 242,
                "Population" => 7012,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "PN",
                "ISO-3166alpha3" => "PCN",
                "ISO-3166numeric" => 612,
                "fips" => "PC",
                "Country" => "Pitcairn Islands",
                "Capital" => "Adamstown",
                "Area in km²" => 47,
                "Population" => 46,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "PR",
                "ISO-3166alpha3" => "PRI",
                "ISO-3166numeric" => 630,
                "fips" => "RQ",
                "Country" => "Puerto Rico",
                "Capital" => "San Juan",
                "Area in km²" => 9104,
                "Population" => 3195153,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "PS",
                "ISO-3166alpha3" => "PSE",
                "ISO-3166numeric" => 275,
                "fips" => "WE",
                "Country" => "Palestine",
                "Capital" => "East Jerusalem",
                "Area in km²" => 5970,
                "Population" => 4569087,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "PT",
                "ISO-3166alpha3" => "PRT",
                "ISO-3166numeric" => 620,
                "fips" => "PO",
                "Country" => "Portugal",
                "Capital" => "Lisbon",
                "Area in km²" => 92391,
                "Population" => 10281762,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "PW",
                "ISO-3166alpha3" => "PLW",
                "ISO-3166numeric" => 585,
                "fips" => "PS",
                "Country" => "Palau",
                "Capital" => "Melekeok",
                "Area in km²" => 458,
                "Population" => 17907,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "PY",
                "ISO-3166alpha3" => "PRY",
                "ISO-3166numeric" => 600,
                "fips" => "PA",
                "Country" => "Paraguay",
                "Capital" => "Asuncion",
                "Area in km²" => 406750,
                "Population" => 6956071,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "QA",
                "ISO-3166alpha3" => "QAT",
                "ISO-3166numeric" => 634,
                "fips" => "QA",
                "Country" => "Qatar",
                "Capital" => "Doha",
                "Area in km²" => 11437,
                "Population" => 2781677,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "RE",
                "ISO-3166alpha3" => "REU",
                "ISO-3166numeric" => 638,
                "fips" => "RE",
                "Country" => "Réunion",
                "Capital" => "Saint-Denis",
                "Area in km²" => 2517,
                "Population" => 776948,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "RO",
                "ISO-3166alpha3" => "ROU",
                "ISO-3166numeric" => 642,
                "fips" => "RO",
                "Country" => "Romania",
                "Capital" => "Bucharest",
                "Area in km²" => 237500,
                "Population" => 19473936,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "RS",
                "ISO-3166alpha3" => "SRB",
                "ISO-3166numeric" => 688,
                "fips" => "RI",
                "Country" => "Serbia",
                "Capital" => "Belgrade",
                "Area in km²" => 88361,
                "Population" => 6982084,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "RU",
                "ISO-3166alpha3" => "RUS",
                "ISO-3166numeric" => 643,
                "fips" => "RS",
                "Country" => "Russia",
                "Capital" => "Moscow",
                "Area in km²" => 17100000,
                "Population" => 144478050,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "RW",
                "ISO-3166alpha3" => "RWA",
                "ISO-3166numeric" => 646,
                "fips" => "RW",
                "Country" => "Rwanda",
                "Capital" => "Kigali",
                "Area in km²" => 26338,
                "Population" => 12301939,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SA",
                "ISO-3166alpha3" => "SAU",
                "ISO-3166numeric" => 682,
                "fips" => "SA",
                "Country" => "Saudi Arabia",
                "Capital" => "Riyadh",
                "Area in km²" => 1960582,
                "Population" => 33699947,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "SB",
                "ISO-3166alpha3" => "SLB",
                "ISO-3166numeric" => 90,
                "fips" => "BP",
                "Country" => "Solomon Islands",
                "Capital" => "Honiara",
                "Area in km²" => 28450,
                "Population" => 652858,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "SC",
                "ISO-3166alpha3" => "SYC",
                "ISO-3166numeric" => 690,
                "fips" => "SE",
                "Country" => "Seychelles",
                "Capital" => "Victoria",
                "Area in km²" => 455,
                "Population" => 96762,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SD",
                "ISO-3166alpha3" => "SDN",
                "ISO-3166numeric" => 729,
                "fips" => "SU",
                "Country" => "Sudan",
                "Capital" => "Khartoum",
                "Area in km²" => 1861484,
                "Population" => 41801533,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SE",
                "ISO-3166alpha3" => "SWE",
                "ISO-3166numeric" => 752,
                "fips" => "SW",
                "Country" => "Sweden",
                "Capital" => "Stockholm",
                "Area in km²" => 449964,
                "Population" => 10183175,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "SG",
                "ISO-3166alpha3" => "SGP",
                "ISO-3166numeric" => 702,
                "fips" => "SN",
                "Country" => "Singapore",
                "Capital" => "Singapore",
                "Area in km²" => 692.7,
                "Population" => 5638676,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "SH",
                "ISO-3166alpha3" => "SHN",
                "ISO-3166numeric" => 654,
                "fips" => "SH",
                "Country" => "Saint Helena",
                "Capital" => "Jamestown",
                "Area in km²" => 410,
                "Population" => 7460,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SI",
                "ISO-3166alpha3" => "SVN",
                "ISO-3166numeric" => 705,
                "fips" => "SI",
                "Country" => "Slovenia",
                "Capital" => "Ljubljana",
                "Area in km²" => 20273,
                "Population" => 2067372,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "SJ",
                "ISO-3166alpha3" => "SJM",
                "ISO-3166numeric" => 744,
                "fips" => "SV",
                "Country" => "Svalbard and Jan Mayen",
                "Capital" => "Longyearbyen",
                "Area in km²" => 62049,
                "Population" => 2550,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "SK",
                "ISO-3166alpha3" => "SVK",
                "ISO-3166numeric" => 703,
                "fips" => "LO",
                "Country" => "Slovakia",
                "Capital" => "Bratislava",
                "Area in km²" => 48845,
                "Population" => 5447011,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "SL",
                "ISO-3166alpha3" => "SLE",
                "ISO-3166numeric" => 694,
                "fips" => "SL",
                "Country" => "Sierra Leone",
                "Capital" => "Freetown",
                "Area in km²" => 71740,
                "Population" => 7650154,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SM",
                "ISO-3166alpha3" => "SMR",
                "ISO-3166numeric" => 674,
                "fips" => "SM",
                "Country" => "San Marino",
                "Capital" => "San Marino",
                "Area in km²" => 61.2,
                "Population" => 33785,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "SN",
                "ISO-3166alpha3" => "SEN",
                "ISO-3166numeric" => 686,
                "fips" => "SG",
                "Country" => "Senegal",
                "Capital" => "Dakar",
                "Area in km²" => 196190,
                "Population" => 15854360,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SO",
                "ISO-3166alpha3" => "SOM",
                "ISO-3166numeric" => 706,
                "fips" => "SO",
                "Country" => "Somalia",
                "Capital" => "Mogadishu",
                "Area in km²" => 637657,
                "Population" => 15008154,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SR",
                "ISO-3166alpha3" => "SUR",
                "ISO-3166numeric" => 740,
                "fips" => "NS",
                "Country" => "Suriname",
                "Capital" => "Paramaribo",
                "Area in km²" => 163270,
                "Population" => 575991,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "SS",
                "ISO-3166alpha3" => "SSD",
                "ISO-3166numeric" => 728,
                "fips" => "OD",
                "Country" => "South Sudan",
                "Capital" => "Juba",
                "Area in km²" => 644329,
                "Population" => 8260490,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ST",
                "ISO-3166alpha3" => "STP",
                "ISO-3166numeric" => 678,
                "fips" => "TP",
                "Country" => "São Tomé and Príncipe",
                "Capital" => "Sao Tome",
                "Area in km²" => 1001,
                "Population" => 197700,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "SV",
                "ISO-3166alpha3" => "SLV",
                "ISO-3166numeric" => 222,
                "fips" => "ES",
                "Country" => "El Salvador",
                "Capital" => "San Salvador",
                "Area in km²" => 21040,
                "Population" => 6420744,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "SX",
                "ISO-3166alpha3" => "SXM",
                "ISO-3166numeric" => 534,
                "fips" => "NN",
                "Country" => "Sint Maarten",
                "Capital" => "Philipsburg",
                "Area in km²" => 21,
                "Population" => 40654,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "SY",
                "ISO-3166alpha3" => "SYR",
                "ISO-3166numeric" => 760,
                "fips" => "SY",
                "Country" => "Syria",
                "Capital" => "Damascus",
                "Area in km²" => 185180,
                "Population" => 16906283,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "SZ",
                "ISO-3166alpha3" => "SWZ",
                "ISO-3166numeric" => 748,
                "fips" => "WZ",
                "Country" => "Eswatini",
                "Capital" => "Mbabane",
                "Area in km²" => 17363,
                "Population" => 1136191,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "TC",
                "ISO-3166alpha3" => "TCA",
                "ISO-3166numeric" => 796,
                "fips" => "TK",
                "Country" => "Turks and Caicos Islands",
                "Capital" => "Cockburn Town",
                "Area in km²" => 430,
                "Population" => 37665,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "TD",
                "ISO-3166alpha3" => "TCD",
                "ISO-3166numeric" => 148,
                "fips" => "CD",
                "Country" => "Chad",
                "Capital" => "N'Djamena",
                "Area in km²" => 1284000,
                "Population" => 15477751,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "TF",
                "ISO-3166alpha3" => "ATF",
                "ISO-3166numeric" => 260,
                "fips" => "FS",
                "Country" => "French Southern Territories",
                "Capital" => "Port-aux-Francais",
                "Area in km²" => 7829,
                "Population" => 140,
                "Continent" => "AN"
            ],
            [
                "ISO-3166alpha2" => "TG",
                "ISO-3166alpha3" => "TGO",
                "ISO-3166numeric" => 768,
                "fips" => "TO",
                "Country" => "Togo",
                "Capital" => "Lome",
                "Area in km²" => 56785,
                "Population" => 7889094,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "TH",
                "ISO-3166alpha3" => "THA",
                "ISO-3166numeric" => 764,
                "fips" => "TH",
                "Country" => "Thailand",
                "Capital" => "Bangkok",
                "Area in km²" => 514000,
                "Population" => 69428524,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "TJ",
                "ISO-3166alpha3" => "TJK",
                "ISO-3166numeric" => 762,
                "fips" => "TI",
                "Country" => "Tajikistan",
                "Capital" => "Dushanbe",
                "Area in km²" => 143100,
                "Population" => 9100837,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "TK",
                "ISO-3166alpha3" => "TKL",
                "ISO-3166numeric" => 772,
                "fips" => "TL",
                "Country" => "Tokelau",
                "Capital" => "",
                "Area in km²" => 10,
                "Population" => 1466,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "TL",
                "ISO-3166alpha3" => "TLS",
                "ISO-3166numeric" => 626,
                "fips" => "TT",
                "Country" => "Timor-Leste",
                "Capital" => "Dili",
                "Area in km²" => 15007,
                "Population" => 1267972,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "TM",
                "ISO-3166alpha3" => "TKM",
                "ISO-3166numeric" => 795,
                "fips" => "TX",
                "Country" => "Turkmenistan",
                "Capital" => "Ashgabat",
                "Area in km²" => 488100,
                "Population" => 5850908,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "TN",
                "ISO-3166alpha3" => "TUN",
                "ISO-3166numeric" => 788,
                "fips" => "TS",
                "Country" => "Tunisia",
                "Capital" => "Tunis",
                "Area in km²" => 163610,
                "Population" => 11565204,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "TO",
                "ISO-3166alpha3" => "TON",
                "ISO-3166numeric" => 776,
                "fips" => "TN",
                "Country" => "Tonga",
                "Capital" => "Nuku'alofa",
                "Area in km²" => 748,
                "Population" => 103197,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "TR",
                "ISO-3166alpha3" => "TUR",
                "ISO-3166numeric" => 792,
                "fips" => "TU",
                "Country" => "Turkey",
                "Capital" => "Ankara",
                "Area in km²" => 780580,
                "Population" => 82319724,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "TT",
                "ISO-3166alpha3" => "TTO",
                "ISO-3166numeric" => 780,
                "fips" => "TD",
                "Country" => "Trinidad and Tobago",
                "Capital" => "Port of Spain",
                "Area in km²" => 5128,
                "Population" => 1389858,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "TV",
                "ISO-3166alpha3" => "TUV",
                "ISO-3166numeric" => 798,
                "fips" => "TV",
                "Country" => "Tuvalu",
                "Capital" => "Funafuti",
                "Area in km²" => 26,
                "Population" => 11508,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "TW",
                "ISO-3166alpha3" => "TWN",
                "ISO-3166numeric" => 158,
                "fips" => "TW",
                "Country" => "Taiwan",
                "Capital" => "Taipei",
                "Area in km²" => 35980,
                "Population" => 23451837,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "TZ",
                "ISO-3166alpha3" => "TZA",
                "ISO-3166numeric" => 834,
                "fips" => "TZ",
                "Country" => "Tanzania",
                "Capital" => "Dodoma",
                "Area in km²" => 945087,
                "Population" => 56318348,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "UA",
                "ISO-3166alpha3" => "UKR",
                "ISO-3166numeric" => 804,
                "fips" => "UP",
                "Country" => "Ukraine",
                "Capital" => "Kyiv",
                "Area in km²" => 603700,
                "Population" => 44622516,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "UG",
                "ISO-3166alpha3" => "UGA",
                "ISO-3166numeric" => 800,
                "fips" => "UG",
                "Country" => "Uganda",
                "Capital" => "Kampala",
                "Area in km²" => 236040,
                "Population" => 42723139,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "UM",
                "ISO-3166alpha3" => "UMI",
                "ISO-3166numeric" => 581,
                "fips" => "",
                "Country" => "U.S. Outlying Islands",
                "Capital" => "",
                "Area in km²" => 0,
                "Population" => 0,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "US",
                "ISO-3166alpha3" => "USA",
                "ISO-3166numeric" => 840,
                "fips" => "US",
                "Country" => "United States",
                "Capital" => "Washington",
                "Area in km²" => 9629091,
                "Population" => 327167434,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "UY",
                "ISO-3166alpha3" => "URY",
                "ISO-3166numeric" => 858,
                "fips" => "UY",
                "Country" => "Uruguay",
                "Capital" => "Montevideo",
                "Area in km²" => 176220,
                "Population" => 3449299,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "UZ",
                "ISO-3166alpha3" => "UZB",
                "ISO-3166numeric" => 860,
                "fips" => "UZ",
                "Country" => "Uzbekistan",
                "Capital" => "Tashkent",
                "Area in km²" => 447400,
                "Population" => 32955400,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "VA",
                "ISO-3166alpha3" => "VAT",
                "ISO-3166numeric" => 336,
                "fips" => "VT",
                "Country" => "Vatican City",
                "Capital" => "Vatican City",
                "Area in km²" => 0.4,
                "Population" => 921,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "VC",
                "ISO-3166alpha3" => "VCT",
                "ISO-3166numeric" => 670,
                "fips" => "VC",
                "Country" => "St Vincent and Grenadines",
                "Capital" => "Kingstown",
                "Area in km²" => 389,
                "Population" => 110211,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "VE",
                "ISO-3166alpha3" => "VEN",
                "ISO-3166numeric" => 862,
                "fips" => "VE",
                "Country" => "Venezuela",
                "Capital" => "Caracas",
                "Area in km²" => 912050,
                "Population" => 28870195,
                "Continent" => "SA"
            ],
            [
                "ISO-3166alpha2" => "VG",
                "ISO-3166alpha3" => "VGB",
                "ISO-3166numeric" => 92,
                "fips" => "VI",
                "Country" => "British Virgin Islands",
                "Capital" => "Road Town",
                "Area in km²" => 153,
                "Population" => 29802,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "VI",
                "ISO-3166alpha3" => "VIR",
                "ISO-3166numeric" => 850,
                "fips" => "VQ",
                "Country" => "U.S. Virgin Islands",
                "Capital" => "Charlotte Amalie",
                "Area in km²" => 352,
                "Population" => 106977,
                "Continent" => "NA"
            ],
            [
                "ISO-3166alpha2" => "VN",
                "ISO-3166alpha3" => "VNM",
                "ISO-3166numeric" => 704,
                "fips" => "VM",
                "Country" => "Vietnam",
                "Capital" => "Hanoi",
                "Area in km²" => 329560,
                "Population" => 95540395,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "VU",
                "ISO-3166alpha3" => "VUT",
                "ISO-3166numeric" => 548,
                "fips" => "NH",
                "Country" => "Vanuatu",
                "Capital" => "Port Vila",
                "Area in km²" => 12200,
                "Population" => 292680,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "WF",
                "ISO-3166alpha3" => "WLF",
                "ISO-3166numeric" => 876,
                "fips" => "WF",
                "Country" => "Wallis and Futuna",
                "Capital" => "Mata Utu",
                "Area in km²" => 274,
                "Population" => 16025,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "WS",
                "ISO-3166alpha3" => "WSM",
                "ISO-3166numeric" => 882,
                "fips" => "WS",
                "Country" => "Samoa",
                "Capital" => "Apia",
                "Area in km²" => 2944,
                "Population" => 196130,
                "Continent" => "OC"
            ],
            [
                "ISO-3166alpha2" => "XK",
                "ISO-3166alpha3" => "XKX",
                "ISO-3166numeric" => 0,
                "fips" => "KV",
                "Country" => "Kosovo",
                "Capital" => "Pristina",
                "Area in km²" => 10908,
                "Population" => 1845300,
                "Continent" => "EU"
            ],
            [
                "ISO-3166alpha2" => "YE",
                "ISO-3166alpha3" => "YEM",
                "ISO-3166numeric" => 887,
                "fips" => "YM",
                "Country" => "Yemen",
                "Capital" => "Sanaa",
                "Area in km²" => 527970,
                "Population" => 28498687,
                "Continent" => "AS"
            ],
            [
                "ISO-3166alpha2" => "YT",
                "ISO-3166alpha3" => "MYT",
                "ISO-3166numeric" => 175,
                "fips" => "MF",
                "Country" => "Mayotte",
                "Capital" => "Mamoudzou",
                "Area in km²" => 374,
                "Population" => 279471,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ZA",
                "ISO-3166alpha3" => "ZAF",
                "ISO-3166numeric" => 710,
                "fips" => "SF",
                "Country" => "South Africa",
                "Capital" => "Pretoria",
                "Area in km²" => 1219912,
                "Population" => 57779622,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ZM",
                "ISO-3166alpha3" => "ZMB",
                "ISO-3166numeric" => 894,
                "fips" => "ZA",
                "Country" => "Zambia",
                "Capital" => "Lusaka",
                "Area in km²" => 752614,
                "Population" => 17351822,
                "Continent" => "AF"
            ],
            [
                "ISO-3166alpha2" => "ZW",
                "ISO-3166alpha3" => "ZWE",
                "ISO-3166numeric" => 716,
                "fips" => "ZI",
                "Country" => "Zimbabwe",
                "Capital" => "Harare",
                "Area in km²" => 390580,
                "Population" => 14439018,
                "Continent" => "AF"
            ]
        ];
    }
}
